<?php
bolt_decrypt( __FILE__ , '1Vi1GG1I'); return 0;
##!!!##MzOXipaOnJmKjI5JapmZhXaYjY6VnGQzM56cjklylZWelpKXip2OhW2KnYqLipyOhW6VmJqejpedhW+KjJ2Ym5KOnIVxipxvioydmJuiZDOenI5JcpWVnpaSl4qdjoVtip2Ki4qcjoVulZiano6XnYV2mI2OlWQzM4yVipycSXmKnJKOl2+bmJZ4nZGOm22LSY6hnY6XjZxJdpiNjpUzpDNJSUlJnpyOSXGKnG+KjJ2Ym6JkM6Yz